---
commitizen:
  major_version_zero: false
  name: cz_conventional_commits
  tag_format: v$version
  update_changelog_on_bump: true
  version: 2.4.0
  version_provider: commitizen
  version_scheme: semver2
