name: "Docker CLI Build"
description: "Build and optionally push Docker CLI image with provenance support"

inputs:
  version:
    description: "Version to tag the image with (optional)"
    required: false
  commit:
    description: "Commit hash to include in build args"
    required: false
  push:
    description: "Whether to push the image to registry"
    required: false
    default: "false"
  tags:
    description: "Additional tags to apply to the image (comma-separated)"
    required: false
    default: ""
  platforms:
    description: "Platforms to build for (comma-separated)"
    required: false
    default: "linux/amd64,linux/arm64"

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Cosign
      if: ${{ inputs.push == 'true' }}
      uses: sigstore/cosign-installer@v3.9.2

    - name: Log in to Container Registry
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/cli
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,format=long
          ${{ inputs.tags != '' && format('type=raw,value={0}', inputs.tags) || '' }}
          ${{ inputs.version != '' && format('type=raw,value=v{0}', inputs.version) || '' }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./cmd/cli.dockerfile
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          version=${{ inputs.version || 'unknown' }}
          commit=${{ inputs.commit }}
        platforms: ${{ inputs.platforms }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        attest: |
          type=provenance,mode=max
          type=sbom

    - name: Cosign the Docker image with GitHub OIDC Token
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        cosign sign --yes --tlog-upload=true \
          --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
          --certificate-identity-regexp "^https://github.com/${{ github.repository }}/\.github/workflows/.*$" \
          "ghcr.io/${{ github.repository }}/cli@${{ steps.build.outputs.digest }}"

    - name: Verify provenance
      if: ${{ inputs.push == 'true' }}
      shell: bash
      run: |
        cosign verify-attestation \
          --type slsaprovenance \
          --certificate-oidc-issuer https://token.actions.githubusercontent.com \
          --certificate-identity-regexp 'github.com/${{ github.repository }}/\.github/workflows/.*' \
          ghcr.io/${{ github.repository }}/cli@${{ steps.build.outputs.digest }}
