name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  ci:
    name: Continuous Integration
    uses: ./.github/workflows/shared.yaml
    secrets: inherit
